"""initial schema

Revision ID: ad554b622eed
Revises: 
Create Date: 2026-04-11 00:18:04.793714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad554b622eed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('estimated_delivery_time', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('after_hours_message', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=True),
    sa.Column('confirmation_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unavailable_behavior', sa.Enum('SKIP', 'SUGGEST_ALTERNATIVE', 'ASK_CUSTOMER', name='unavailablebehavior', native_enum=False), nullable=False),
    sa.Column('can_suggest_alternatives', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tone', sa.Enum('FORMAL', 'FRIENDLY', 'CASUAL', name='bottone', native_enum=False), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_bot_configs_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_configs')),
    sa.UniqueConstraint('business_id', name=op.f('uq_bot_configs_business_id'))
    )
    op.create_table('business_delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_delivery_zones_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_delivery_zones'))
    )
    with op.batch_alter_table('business_delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_delivery_zones_business_id'), ['business_id'], unique=False)

    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_hours_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_hours')),
    sa.UniqueConstraint('business_id', 'day_of_week', name='uq_business_hours_business_day')
    )
    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_hours_business_id'), ['business_id'], unique=False)

    op.create_table('business_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_policies_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_policies'))
    )
    with op.batch_alter_table('business_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_policies_business_id'), ['business_id'], unique=False)

    op.create_table('business_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_promotions_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_promotions'))
    )
    with op.batch_alter_table('business_promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_promotions_business_id'), ['business_id'], unique=False)

    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('delivery_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('minimum_order_delivery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('free_delivery_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('accept_cash', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('accept_card', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('accept_online', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cash_only_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('require_prepayment', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_settings_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_settings')),
    sa.UniqueConstraint('business_id', name=op.f('uq_business_settings_business_id'))
    )
    op.create_table('business_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'AGENT', 'VIEWER', name='businessrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_users_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_users')),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_business_users_business_user')
    )
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_users_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_users_user_id'), ['user_id'], unique=False)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'DROPPED', 'INCOMPLETE', name='callstatus', native_enum=False), nullable=False),
    sa.Column('resulted_in_order', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_call_logs_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_business_id'), ['business_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_categories_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('business_id', 'name', name='uq_categories_business_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_business_id'), ['business_id'], unique=False)

    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_faqs_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faqs_business_id'), ['business_id'], unique=False)

    op.create_table('menu_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('TIME_RESTRICTION', 'DELIVERY_RULE', 'COMBO_RULE', 'MODIFIER_RULE', 'PAYMENT_RULE', name='menuruletype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_menu_rules_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_rules'))
    )
    with op.batch_alter_table('menu_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_rules_business_id'), ['business_id'], unique=False)

    op.create_table('call_log_error_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], name=op.f('fk_call_log_error_flags_call_log_id_call_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_log_error_flags'))
    )
    with op.batch_alter_table('call_log_error_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_log_error_flags_call_log_id'), ['call_log_id'], unique=False)

    op.create_table('call_log_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], name=op.f('fk_call_log_tool_calls_call_log_id_call_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_log_tool_calls'))
    )
    with op.batch_alter_table('call_log_tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_log_tool_calls_call_log_id'), ['call_log_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=True),
    sa.Column('folio', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('PICKUP', 'DELIVERY', name='ordertype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'ONLINE', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('ai_call_summary', sa.Text(), nullable=True),
    sa.Column('transcript_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_orders_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], name=op.f('fk_orders_call_log_id_call_logs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_call_log_id'), ['call_log_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_folio'), ['folio'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_sold_out', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_products_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('changed_by_type', sa.Enum('SYSTEM', 'USER', 'BOT', name='changedbytype', native_enum=False), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_order_status_history_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_changed_by_user_id'), ['changed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    op.create_table('product_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_modifiers_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_modifiers'))
    )
    with op.batch_alter_table('product_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_modifiers_product_id'), ['product_id'], unique=False)

    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_modifier_id', sa.Integer(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_order_item_modifiers_order_item_id_order_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_modifier_id'], ['product_modifiers.id'], name=op.f('fk_order_item_modifiers_product_modifier_id_product_modifiers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_item_modifiers'))
    )
    with op.batch_alter_table('order_item_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_modifiers_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_modifiers_product_modifier_id'), ['product_modifier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_modifiers_product_modifier_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_modifiers_order_item_id'))

    op.drop_table('order_item_modifiers')
    with op.batch_alter_table('product_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_modifiers_product_id'))

    op.drop_table('product_modifiers')
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_status_history_changed_by_user_id'))

    op.drop_table('order_status_history')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_business_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_folio'))
        batch_op.drop_index(batch_op.f('ix_orders_call_log_id'))
        batch_op.drop_index(batch_op.f('ix_orders_business_id'))

    op.drop_table('orders')
    with op.batch_alter_table('call_log_tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_log_tool_calls_call_log_id'))

    op.drop_table('call_log_tool_calls')
    with op.batch_alter_table('call_log_error_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_log_error_flags_call_log_id'))

    op.drop_table('call_log_error_flags')
    with op.batch_alter_table('menu_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_rules_business_id'))

    op.drop_table('menu_rules')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faqs_business_id'))

    op.drop_table('faqs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_business_id'))

    op.drop_table('categories')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_business_id'))

    op.drop_table('call_logs')
    with op.batch_alter_table('business_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_business_users_business_id'))

    op.drop_table('business_users')
    op.drop_table('business_settings')
    with op.batch_alter_table('business_promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_promotions_business_id'))

    op.drop_table('business_promotions')
    with op.batch_alter_table('business_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_policies_business_id'))

    op.drop_table('business_policies')
    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_hours_business_id'))

    op.drop_table('business_hours')
    with op.batch_alter_table('business_delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_delivery_zones_business_id'))

    op.drop_table('business_delivery_zones')
    op.drop_table('bot_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('businesses')
    # ### end Alembic commands ###
